### ISSUE TITLE
Lookup service should force HTTPS when secure ingress available.

### ISSUE THREAD

**Issue by GrahamDumpleton** [educates/educates-training-platform#549]
### Describe the bug

Ingress for lookup service needs to add https redirection annotations when secure ingress available.

```
annotations:
   ingress.kubernetes.io/force-ssl-redirect: "true"
   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
   nginx.ingress.kubernetes.io/ssl-redirect: "true"
```
