### ISSUE TITLE
Resolved images from kbld not passed through in educates-config config map.

### ISSUE THREAD

**Issue by GrahamDumpleton** [educates/educates-training-platform#605]
### Describe the bug

The `educates-config` config map in `educates` namespace has a sections for `imageVersions`. This provides mappings for locations for images. Before 3.0 refactor for deployment, the mapped to image would have `sha` reference from `kbld` for images. This is no longer the case and is now just passed through like:

```
    imageVersions:
    - name: session-manager
      image: ghcr.io/educates/educates-session-manager:3.1.0-rc.1
    - name: training-portal
      image: ghcr.io/educates/educates-training-portal:3.1.0-rc.1
```

Consequence is that disconnected installs would no longer work where images were all copied into an internal registry using `imgpkg copy`.
