### ISSUE TITLE
Ingresses don't support secure option.

### ISSUE THREAD

**Issue by GrahamDumpleton** [educates/educates-training-platform#637]
### Describe the bug

Docs has example:

```
spec:
  session:
    ingresses:
    - name: application
      protocol: https
      host: service.$(session_namespace).svc.$(cluster_domain)
      secure: false
```

but the `secure` option is rejected by the CRD spec.
