### ISSUE TITLE
secrets-manager complains about missing RBAC permissions in 3.2.0

### ISSUE THREAD

**Issue by mocdaniel** [educates/educates-training-platform#670]
### Describe the bug

When inspecting the logs of the `secrets-manager` workload after deploying the provided kapp App, it complains about missing permissions on the `customresourcedefinitions` resource in the `apiextensions.k8s.io` API group.

I could fix this by adding the following item to the `rules` list of the `educates-secrets-manager` ClusterRole:

```yaml
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - watch
  - list
```

Not sure whether this is a false positive and can be ignored, or if the adjustment to the ClusterRole is actually needed.

### Additional information

Educates Version: v3.2.0
