### ISSUE TITLE
Allow aliases for workshops listed in a training portal.

### ISSUE THREAD

**Issue by GrahamDumpleton** [educates/educates-training-platform#722]
### Is your feature request related to a problem? Please describe.

The training portal allows `env` settings to be overridden for workshops, but the `name` field (name of `Workshop` definition) has to be unique for each workshop. This means I can't have multiple workshops listed which use the same `name` but have different `env` overrides to customise the workshop.

### Describe the solution you'd like

Allow an `alias` property to be supplied which overrides the `name` property and thus how the workshop is identified via the REST API when requesting a workshop. This means can do:

```yaml
spec:
  workshops:
  - name: lab-coding-sample
    alias: lab-java-sample
    env:
    - name: PROGRAMMING_LANGUAGE
      value: Java
  - name: lab-coding-sample
    alias: lab-python-sample
    env:
    - name: PROGRAMMING_LANGUAGE
      value: Python
```

That is, use same `Workshop` definition in multiple workshops with `env` overrides.

This avoids the need to make a copy of the `Workshop` definition under a different name.
