### ISSUE TITLE
Add ability to mount secrets for extensions to be used in setup.d

### ISSUE THREAD

**Issue by jorgemoralespou** [educates/educates-training-platform#754]
### Is your feature request related to a problem? Please describe.

Currently extension packages uses vendir, so the secrets that are provided to the image sections of a package are used as credentials for vendir, but when you want to add a secret for external configuration so that the extension can be configured, this won't work.

I have come up with the following snippet for a continue.dev extension:
```
  workshop:
    files:
    - image:
        url: "$(image_repository)/sample-stacklok-workshop-files:$(workshop_version)"
      includePaths:
      - /workshop/**
    packages:
      - name: vscode-continue-dev
        files:
          - path: extension
            image:
              url: $(image_repository)/vscode-continue-dev:v1.1.52
          - path: config
            inline:
              pathsFrom:
              - secretRef:
                  name: continue-litellm-config
  environment:
    secrets:
    - name: continue-litellm-config
      namespace: default   
```

Then the secret has:
```
apiVersion: v1
kind: Secret
metadata:
  name: continue-litellm-config
  namespace: default
type: Opaque
stringData:
  continue-litellm-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #! Continue.dev configuration for LiteLLM

    #@overlay/match by=overlay.all, expects="1+"
    ---
    models:
      - name: LiteLLM
        provider: openrouter
        model: gemini/gemini-2.5-flash
        apiBase: http://litellm.litellm.svc.cluster.local:4000
        apiKey: sk-XYZ
        roles:
          - chat
          - edit
          - apply
```

And the `setup.d` script would use this secret to configure an extension file. 
```
ytt -f ~/.continue/config.yaml.bak -f $PACKAGE_DIR/config/ > ~/.continue/config.yaml
```

But then, the `setup.d` in the extension folder is not run, as it expects to be one level up.

How can I provide an external file in a secret so that the extension can use it to configure itself at setup.d time?

### Describe the solution you'd like

I'd like an easy way to be able to provide external configuration (via a secret) to an extension so that it's configured at setup time.
